M48
; DRILL file {KiCad (6.0.8)} date Sat Oct  8 06:19:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-08T06:19:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.175
%
G90
G05
T1
X162.56Y-101.6
X163.83Y-53.34
X214.63Y-68.58
X214.63Y-96.52
T0
M30
